name: 'Close stale issues and PRs'

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write

    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 60
          days-before-close: 7
          # issue
          exempt-issue-labels: 'enhancement,bug,needs examples,needs documentation,work-in-progress'
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
          close-issue-message: 'This issue is closed because there has been no recent activity.'
          # pr
          exempt-pr-labels: 'dependencies,enhancement,bug,needs examples,needs documentation,work-in-progress'
          stale-pr-message: 'This PR has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
          close-pr-message: 'This PR is closed because there has been no recent activity.'
          exempt-draft-pr: true
